wzimongus/wzimongus

- scenes/ui/chat/chat.gd
- scenes/ui/voting_screen/voting_screen.gd
- scenes/ui/voting_screen/voting_screen.tscn
This pull request introduces a new feature to the system by adding a chat window to the voting screen. The purpose of this feature is to allow users to communicate and exchange information during the voting process, enhancing community interaction and engagement.
1. Chat Window Addition: Introduces a new chat window component visible on the voting screen. Users can utilize this window to send text messages, ask questions, or provide responses.
2. Interactivity: The chat window is interactive, enabling users to quickly and easily browse and respond to messages from other participants.
> Feature: Chat in Voting Screen

- scenes/maps/main_map/main_map.tscn
- scenes/minigames/room_reservations/RoomReservations.gd
- scenes/minigames/room_reservations/RoomReservations.tscn
- scenes/minigames/room_reservations/room_node/RoomNode.gd
- scenes/minigames/room_reservations/room_node/RoomNode.tscn
- scenes/ui/minigame_menu/minigame_menu.gd
This pull request introduces an exciting new feature to the system: the Room Reservations Minigame. The primary objective is to offer users an interactive and enjoyable way to engage with the platform while simulating the process of reserving rooms.
> Feature: Minigame: Room Reservations Minigame

- globals/game_manager/game_manager.gd
- scenes/maps/main_map/scenes/task_button/task_button.gd
- scenes/maps/main_map/scenes/vent/vent.gd
- scenes/player/player.gd
- scenes/ui/loading_screen/loading_screen.gd
- scenes/ui/user_interface/user_interface.gd
- scenes/ui/user_interface/user_interface.tscn
Greetings, coding connoisseurs! 🚀 In this celestial pull request, I present to you the awe-inspiring masterpiece born from the `feature/connect-ui` branch – a quantum leap in user interface connectivity and unparalleled button prowess!
Witness the magic of the Vent Button – now intricately woven into the very fabric of the UI. With this feature, users can unleash their thoughts and emotions into the digital cosmos at the mere click of a button. Let the ideas flow like stardust!
Prepare yourselves for the grandeur of the Fail Button – now intergalactically connected. Frustrations, setbacks, and hilarious mishaps can be broadcasted to the universe with unmatched efficiency. Failure has never been this mesmerizing!
As if the cosmic connection wasn't enough, we've introduced the Fail Button …
> Feature: Connect UI

- scenes/maps/main_map/main_map.tscn
> Fixed Y-Sort - fix #91

- scenes/player/skin_selection.gd
> Fixed #105

- scenes/maps/main_map/main_map.tscn
Hark! Attend to this humble request, ye guardians of the code!
I, a skilled artisan in the realm of coding, doth present to thee a fix for the vexing Issue #112 that hath plagued our software.
In this quest, the feature that doth allow students to vent in two vents hath been deemed unfit for our code kingdom. This hath been corrected with diligence and care.
The treacherous bug, known as Issue #112, did allow students the usage of vent, causing great chaos and confusion in our digital halls. This pull request doth bring forth the necessary amendments to suppress such unruly behavior.
Methinks the changes made are righteous and just. Pray, review with a discerning eye, and merge them into the main branch to restore order in our codebase.
May this humble pull request find favor in the eyes …
> turned off allow student venting in two vents

- scenes/player/player.gd
- scenes/player/player.tscn
Jako że to ostatni dzisiaj merge, to polecam każdemu iść spać.
> Fix issue#116

- scenes/maps/lobby/lobby.tscn
- scenes/maps/main_map/main_map.tscn
- scenes/minigames/copying-files/copying_files.gd
- scenes/minigames/copying-files/copying_files.tscn
- scenes/minigames/correct_combination/correct_combination.gd
- scenes/minigames/correct_combination/correct_combination.tscn
- scenes/minigames/fill_formulas/fill_formulas.gd
- scenes/minigames/fill_formulas/fill_formulas.tscn
- scenes/minigames/graph_the_function/assets/scripts/graph_the_function.gd
- scenes/minigames/graph_the_function/graph_the_function.tscn
- scenes/minigames/make_a_photo/make_a_photo.gd
- scenes/minigames/make_a_photo/make_a_photo.tscn
- scenes/minigames/reactor_memory_answer/reactor_memory_answer.gd
- scenes/minigames/reactor_memory_answer/reactor_memory_answer.tscn
- scenes/minigames/room_reservations/RoomReservations.gd
- scenes/minigames/room_reservations/RoomReservations.tscn
- scenes/ui/task_list_display/task_list_display.gd
Now you can view all the task in the most beautiful language of them all. Yeah, you guessed it correct even though you've probably read the title. IT'S POLISH :poland: TIME BABY :baby: !!! And to add up onto that, those names were translated by none other than your foreign friend to add a little spice to it :skull: 
* Task names on the screen are now displayed in Polish :poland:
> Feature: Polish Task Names

- scenes/maps/main_map/main_map.gd
- scenes/maps/main_map/main_map.tscn
- scenes/maps/main_map/scenes/report/emergency_button/emergency_button.gd
- scenes/maps/main_map/scenes/report/emergency_button/emergency_button.tscn
- scenes/maps/main_map/scenes/report/report_screen/report_screen.gd
- scenes/maps/main_map/scenes/report/report_screen/report_screen.tscn
- scenes/player/assets/dead_body.gd
- scenes/player/player.gd
- scenes/ui/minigame_menu/minigame_menu.gd
- scenes/ui/minigame_menu/minigame_menu.tscn
- scenes/ui/start_menu/background/background.gd
- scenes/ui/voting_screen/voting_screen.gd
🚀✨✨✨ Pull Request:` Feature/Report-Improvements` → `Main` ✨✨✨ 🚀
👋🏽 Hello fellow collaborators! 🤝
🎉🌟 I'm thrilled to present to you the fantastic enhancements from the` feature/report-improvements` branch! 🚀🌈
Changes included in this feature:
🐛 Fixed the pesky issue when attempting to report the lifeless body of a player who decided to peace out! 🚪💔 No more bugs here!
🎥 Added some fancy animations to the report screen to make reporting more engaging and visually pleasing! 🕺💃🎬 Get ready for a cinematic reporting experience!
🧹 Removed redundant code that was just cluttering up the codebase like a messy game room! 🚮🧽 Less is more, right?
Why you'll love this pull request:
🚀 Boosts reporting efficiency!
🎉 Enhances user experience!
🚮 Declutters the codebase!
This pull request has been …
> Feature: Report Improvemets

- scenes/ui/start_menu/background/background.gd
🔮 Greetings, fellow wizards and enchanters of the Code Realm!🌟 I present unto thee a majestic elixir to mend the mystical quirk in our enchantments. 🧙‍♂️✨
A bug has dared to infiltrate our enchanted repository, known as `issue#126`, wherein the selection of new background images mirrors the past. 🤔🌈 Fear not, for my arcane arts have conjured a remedy that ensures the images shall dance with unparalleled uniqueness! 🎭💫
Behold the enchanted branches, where the spell of `bugfix/issue#126` has been diligently woven. 🌿🔗 I have tested this magical potion and can affirm its potency against the mischievous bug that plagued our abode.
By your leave, mighty stewards of the Code Citadel, I beseech thee to cast your discerning gaze upon the humble plea below:
**From:** `bugfix/issue#126`
**To:** …
> Bugfix: Issue #126

- globals/game_manager/game_manager.gd
- scenes/player/player.gd
* Impostors now can turn off the lights.
* If sabotage is activated from one impostor, then other impostors will get a cooldown too.
* You can't do sabotages while inside the vent, just because...
* Sabotage lasts 10 seconds or if sabotage cooldown is less than 10 seconds than it will last sabotage cooldown seconds
> Feature: Light sabotage

- globals/game_manager/game_manager.gd
- scenes/maps/lobby/scenes/lobby_settings/lobby_settings.gd
- scenes/maps/lobby/scenes/lobby_settings/lobby_settings.tscn
- scenes/minigames/copying-files/copying_files.tscn
- scenes/ui/settings/settings.gd
This pull request, titled `feature/minigame/lobby-settings-improvement`, is proposed for merging into the `main` branch. It encompasses the addition of three new options in the lobby settings, a change in the size of Nodes on Input, and the correction of several typographical errors.
1. **New Options in Lobby Settings**: Three additional options have been integrated into the lobby settings.
2. **Node Size Adjustment on Input**: The size of Nodes on Input has been altered.
3. **Typographical Error Corrections**: A number of spelling mistakes have been rectified.
- The new options in the lobby settings are intended to provide more choices to the user.
- Adjusting the size of Nodes on Input is aimed at standardizing their dimensions.
- Correcting typographical errors is for clarity and …
> Update: Lobby Settings - Addition of Three Options, Node Size Adjustment, and Typo Corrections

- scenes/player/assets/dead_body.tscn
- scenes/player/player.tscn
Greetings, team! With great excitement, I present to you the `feature/light-improvements` branch, ready for merging into `main`. This update is a game-changer, enhancing player experience by leaps and bounds. Say goodbye to pesky visibility issues and hello to a more immersive and strategically demanding gameplay!
- **Fixed Issue #145**: This stubborn bug is no more! Players can now enjoy the game as intended.
- **Player Visibility Through Walls Resolved**: We've tackled the ghosting players! No more seeing opponents through walls when your player light shouldn't allow it.
- **Player Illumination Bug Fixed**: Those odd illuminations of players in the dark? History! Light behaves realistically now.
- **Dead Body Visibility Adjusted**: No more omnipresent vision of deceased comrades. If …
> Feature: Light Improvements

- scenes/minigames/room_reservations/RoomReservations.gd
> Update room names

- scenes/minigames/find_password/page_scenes/page_scene.gd
- scenes/minigames/find_password/page_scenes/page_scene.tscn
Zamieniono, że zamiast klikać ESCAPE jest po prostu Close Przycisk
> Change exit from ESC to Close Button

- globals/game_manager/game_manager.gd
- scenes/maps/lobby/scenes/lobby_settings/lobby_settings.gd
- scenes/maps/lobby/scenes/lobby_settings/lobby_settings.tscn
- scenes/maps/main_map/main_map.tscn
- scenes/ui/chat/chat.gd
- scenes/ui/minigame_menu/minigame_window.tscn
- scenes/ui/voting_screen/voting_screen.gd
> Minor improvements to voting and lobby_settings

- scenes/ui/loading_screen/loading_screen.tscn
- scenes/ui/voting_screen/voting_screen.tscn
> Add polish text

- scenes/maps/main_map/main_map.tscn
> update main_map.tscn : fix #89

- scenes/minigames/correct_combination/correct_combination.gd
Od teraz jest tylko 5 przełączników poprawnych, gdzie każda odpala jedną kontrolkę
Naprawia w ten sposób issue #179
> Ułatwienie gry Poprawna Kombinacja

- globals/game_manager/game_manager.gd
- scenes/maps/lobby/scenes/lobby_settings/lobby_settings.tscn
- scenes/maps/main_map/scenes/report/report_screen/report_screen.gd
- scenes/ui/credits/credits.gd
- scenes/ui/pause_menu/pause_menu.gd
- scenes/ui/pop_up_window/pop_up_window.gd
- scenes/ui/settings/key_rebind/key_rebind.gd
- scenes/ui/settings/settings.gd
- scenes/ui/settings/user_settings_manager.gd
- scenes/ui/start_menu/background/background.gd
- scenes/ui/start_menu/start_menu.gd
- scenes/ui/user_interface/user_interface.gd
- scenes/ui/window_animation_player/window_animation_player.gd
Hey 👋, team! 🚧 I've crafted an amazing 🌈 pull request that adds ✨ documentation and makes some variables 🔒 private. Take a look 👀 and let's make our codebase even more fabulous! 🎉
- 📚 Added comprehensive documentation for qsqus-script 🖋️.
- 🔐 Made certain variables private for enhanced security 🔒.
- 🌐 Enhanced readability and understanding with detailed documentation.
- 🔐 Strengthened code security by privatizing sensitive variables.
1. 🛑 Check out this branch locally.
2. 🚀 Run the script with various inputs.
3. 🧐 Verify that documentation is clear and variables are appropriately private.
4. 👍 Provide feedback on any improvements.
- 📖 Clear documentation helps everyone understand the code.
- 🔒 Protecting variables enhances the overall security of our application.
- 🤝 Collaborators, your …
> Documentation : qsqus Sscript

- globals/game_manager/game_manager.gd
- globals/task_manager/task_manager.gd
- scenes/game/game.gd
- scenes/maps/main_map/scenes/task_button/task_button.gd
- scenes/maps/main_map/scenes/vent/vent.gd
- scenes/player/player.gd
- scenes/ui/task_list_display/task_list_display.gd
Code documentation and small clean up of TaskManager, TaskButton, Light and Light Sabotage functionalities.
> Documentation: Add documentation to TaskManager, TaskButton, Light and Light Sabotage functionalities.

- globals/game_manager/game_manager.gd
- scenes/player/assets/dead_body.gd
- scenes/player/assets/dead_body.tscn
- scenes/player/player.gd
- scenes/player/player.tscn
- scenes/ui/host_menu/host_menu.tscn
- scenes/ui/join_menu/join_menu.tscn
Hello, fellow Gitnauts! :wave:
Prepare to be dazzled! :star2: Today, I present to you a *groundbreaking* pull request that will revolutionize the way we handle usernames in our beloved project. Get ready to merge the `feature/username-handling` branch into our sacred `main` branch. :tada:
- **Unique Nicknames** :point_up: (Fix #5)
- I've slayed the dragon of duplicate usernames! Now, each nickname is as unique as a snowflake in the Sahara. No more identity crises!
- **Length Matters** :straight_ruler: (Fix #139)
- Precision engineering applied to nickname lengths. Not too long to bore, not too short to ignore! They're just right, Goldilocks-style.
- **Centralized Error Messages** :loudspeaker:
- Say goodbye to scattered error messages! I've herded them like cats into a cozy, centralized …
> Feature: Username Handling

- scenes/maps/lobby/scenes/lobby_settings/lobby_settings.tscn
- scenes/maps/main_map/main_map.tscn
- scenes/minigames/unscrew-whiteboard/unscrew_whiteboard.gd
> Added unsrew whiteboard minigame to `main_map.tscn`

- scenes/maps/main_map/scenes/report/emergency_button/emergency_button.gd
> Bugfix: Issue#213

- scenes/player/player.gd
Ladies and gentlemen, fans of the coding arena, we are gathered here today to witness a monumental clash between `bugfix/issue#204` and `main`. Issue #204, a sneaky player in our codebase, prevented our users from unleashing their strategic genius - using the sabotage button while masterfully hidden in a vent. But fear not! Our star player, `bugfix/issue#204`, is here to change the game!
- Opponent: A tricky bug in the system, akin to a goalie blocking every shot.
- Playing Field: The inability to use the sabotage button while in a vent.
- Score So Far: Bug - 1, Users - 0.
- Star Player: `bugfix/issue#204`.
- Strategy: A masterful play of code, elegantly weaving through layers of logic to re-enable the sabotage button while in a vent.
- Expected Score: Bug - 1, Users - 1.
- On the Field: …
> Bugfix: Issue #204

- globals/game_manager/game_manager.gd
- project.godot
- scenes/game/game.gd
- scenes/game/maps/main_map/main_map.gd
- scenes/menu/host_menu/host_menu.gd
- scenes/menu/host_menu/host_menu.tscn
- scenes/menu/join_menu/join_menu.gd
- scenes/menu/join_menu/join_menu.tscn
- scenes/menu/play_menu/play_menu.tscn
Greetings, brilliant minds! 🌟 Today marks a stellar day in our development journey. I'm super thrilled to present the pull request to merge `feature/godot-42` into our `main` branch. This isn't just any update; it's a quantum leap for our project!
- **Bump Up to Godot 4.2.x**: Brace yourselves! We're upgrading to Godot 4.2.x, unlocking a universe of new features, optimizations, and bug fixes that will propel our project into a new dimension of awesomeness.
- Updated Godot engine to version 4.2.x.
- Enhanced performance and stability with the new engine.
- Addressed all backward compatibility concerns.
- Rigorous testing to ensure smooth integration.
- **Next-Gen Features**: Godot 4.2.x comes packed with cutting-edge features that will let us create more immersive and dynamic experiences. …
> Bump Godot to 4.2.x

- scenes/characters/player/player.gd
- scenes/ui/settings/settings.tscn
I come bearing gifts of bug fixes, a tale of woe no longer mixes.
Branch `bugfix/issue#219`, oh what a sight,
It's time to merge it into the `main`, alright!
🔧 The issue was a sneaky little critter,
Causing havoc, making our code jitter.
But fear not, for I, the code knight,
Have slain the bug with all my might!
🎶 Let's dance a bugfix boogie, oh so sweet,
In the main branch, where errors shall meet their defeat.
Minor adjustments, settings so fine,
Now our code shines like a diamond mine! 💎
❎ Abracadabra, presto chango,
Bug #219 is now a no-show!
So, dear maintainers, lend me your ear,
Merge this PR, without a fear! 🚢
🌈 Let joy and laughter fill the air,
As we celebrate this bug's despair.
Merge into main, let's make it snappy,
Our codebase now happy and oh-so-sappy! 🌟
> Bugfix: Issue #219

- scenes/game/maps/main_map/emergency_button/emergency_button.gd
Greetings, fellow wanderers of the code abyss. 🌠
In the vast tapestry of our digital existence, I present to you a cryptic offering—a humble pull request that seeks to mend the fabric of reality itself. Behold, the enigma of `bugfix/issue#222` emerges from the shadows.
Within the cosmic dance of commits, elusive alterations have taken place. Mysterious forces have whispered to the codebase, coaxing it to transcend the limitations of its own being. Yet, the details remain veiled, shrouded in ambiguity.
As you venture into the diff, let your consciousness expand beyond the mundane. Question not only the lines of code but the very essence of their existence. What purpose do they serve? What cosmic design unfolds with each alteration?
Merge this pull request and traverse the event horizon …
> Bugfix: Issue #222

- scenes/minigames/unscrew_whiteboard/unscrew_whiteboard.gd
> Bugfix: Issue #230

- globals/game_manager/game_manager.gd
- scenes/characters/player/player.gd
- scenes/game/maps/main_map/emergency_button/emergency_button.gd
- scenes/game/maps/main_map/report_area/report_area.gd
- scenes/game/maps/main_map/vent/vent.gd
---
Meowrge branch `feature/vent-fixes` into `main` for a delightful set of fixes and improvements! 🛠️🐱
---
The report-vent issue was causing a lot of confusion, with hoomans unable to navigate properly. 🚨😿 The emergency button highlight was also misbehaving, sticking around when players vented away. 🚀😾 This led to quite the cat-astrophe in the gaming experience!
---
🔧 **Report-Vent Issue:** Fixed it, so now everything flows smoothly like a ball of yarn! 🧶😸
🔧 **Emergency Button Highlight:** It now vanishes as gracefully as a cat in the shadows! 🌌🐾
---
🚀 Gameplay now has an extra dash of excitement with improved venting mechanics! 😻💨
🚀 We've polished the code, making it as sleek and shiny as a well-groomed fur coat! 🌟🐈
---
- Updated dependencies to ensure a purrfectly harmonious …
> Feature: Vent Fixes

- scenes/characters/player/player.gd
- scenes/game/maps/main_map/task_button/task_button.gd
> Bugfix: Issue #229

- scenes/characters/player/player.gd
- scenes/characters/player/player.tscn
Greetings, Esteemed Code Wizards and Digital Artisans! 🧙‍♂️👩‍💻
I stand before you today, humbly presenting a dazzling enhancement that promises to sprinkle a bit of color into our digital realm. Behold, the **Font Color Override for Lecturer Username Labels**! 🎨🖌
- **Personalization**: Every lecturer becomes a bit more magical with their favorite color dancing around their username.
- **Aesthetic Appeal**: Our platform will now be a mosaic of colors, delighting users and pigeons alike (pigeons love colors, trust me).
- **Morale Boost**: Colors have the power to uplift spirits. Imagine a lecturer's joy upon seeing their name in their favorite teal or majestic purple!
I hereby request the esteemed council of code sorcerers to review this pull request. May your keen eyes and wise hearts …
> Feature: Add font color override for lecturer username label

- scenes/characters/player/player.gd
---
Hello, Illustrious Coders and Visionaries! 🌈👩‍💻👨‍💻
Today, I stand before you with a Pull Request that is nothing short of a quantum leap in our journey towards code excellence. We're about to make history, folks! 🎉
In this PR, I have meticulously removed the archaic and now-redundant *kill screen instantiation* on kill. This change is not just a fix, it's a liberation of our code from the shackles of the past! 🚫💻
I urge you, my fellow code connoisseurs, to review this PR with the keen eye of an eagle and the wisdom of an ancient sage. Let's merge this masterpiece and bask in the glory of our collective genius!
With utmost respect and a dash of excitement,
thedavesky
---
🔥 **Let's make this merge a moment in history!** 🔥
> Bugfix: Fail Logic Change
